%% MelanomaNet deepDreamImage
I = deepDreamImage(MelanomaNet,23,1, ...
    'Verbose',false, ...
    'NumIterations',100);
J = deepDreamImage(MelanomaNet,23,2, ...
    'Verbose',false, ...
    'NumIterations',100);
figure
montage({I,J})
title('Deep Dream Images of MelanomaNet','FontSize',16)